name: Daily File Deletion

on:
  schedule:
    - cron: '35 17 * * *'  # This runs the workflow daily at 5:10 PM South African time

jobs:
  delete_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete files
        run: |
          rm -f image_links.csv
          rm -f listings.csv
          rm -f listings_scrapy.csv
